import type { NextPage } from 'next';
import styles from '../../styles/Home.module.css';
import theme from 'theme';
import { Head, Body, Footer } from 'components';

const Home: NextPage = () => {
	console.log('theme', theme);
	return (
		<div className={styles.container}>
			<Head />
			<Body />
			{/* <Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head> */}
			<Footer />
		</div>
	);
};

export default Home;
